# vim:ft=ansible:
---
- hosts: all
  name: "set up facts"
  tags: common
  tasks:
    - set_fact: scaleio_mdm_primary_ip="{{ hostvars[groups['mdm'][0]]['ansible_'+scaleio_interface]['ipv4']['address'] }}"
    - set_fact: scaleio_mdm_primary_hostname="{{ hostvars[groups['mdm'][0]]['inventory_hostname'] }}"
    - set_fact: scaleio_mdm_secondary_ip="{{ hostvars[groups['mdm'][1]]['ansible_'+scaleio_interface]['ipv4']['address'] }}"
    - set_fact: scaleio_mdm_secondary_hostname="{{ hostvars[groups['mdm'][1]]['inventory_hostname'] }}"

- hosts: all
  name: "Install Common"
  roles:
    - common
  tags: common

- hosts: mdm
  name: "Configure mdm"
  roles:
    - mdm
  tags: mdm

- hosts: tb
  name: "Configure tb"
  roles:
    - tb
  tags: tb

- hosts: gateway
  name: "Configure Gateway"
  roles:
    - gateway
  tags: gateway

- hosts: sds
  name: "Configure sds"
  roles:
    - sds
  tags: sds

- hosts: callhome
  name: "Configure callhome"
  roles:
    - callhome
  tags: callhome

-
  hosts: lia
  name: "Configure lia"
  roles:
    - lia
  tags: lia

-
  hosts: sdc
  name: "Configure sdc"
  roles:
    - sdc
  tags: sdc
