# vim:ft=ansible:
---
- hosts: all
  name: "set up facts"
  tags: always
  tasks:
    - set_fact: scaleio_mdm_primary_ip="{{ hostvars[groups['mdm'][0]]['ansible_'+scaleio_interface]['ipv4']['address'] }}"
    - set_fact: scaleio_mdm_primary_hostname="{{ hostvars[groups['mdm'][0]]['inventory_hostname'] }}"
    - set_fact: scaleio_mdm_secondary_ip="{{ hostvars[groups['mdm'][1]]['ansible_'+scaleio_interface]['ipv4']['address'] }}"
    - set_fact: scaleio_mdm_secondary_hostname="{{ hostvars[groups['mdm'][1]]['inventory_hostname'] }}"
    - set_fact: scaleio_mdm_tertiary_ip="{{ hostvars[groups['mdm'][2]]['ansible_'+scaleio_interface]['ipv4']['address'] }}"
      when: hostvars[groups['mdm'][2]] is defined

    - set_fact: scaleio_mdm_tertiary_hostname="{{ hostvars[groups['mdm'][2]]['inventory_hostname'] }}"
      when: hostvars[groups['mdm'][2]] is defined

    - set_fact: scaleio_tb_primary_ip="{{ hostvars[groups['tb'][0]]['ansible_'+scaleio_interface]['ipv4']['address'] }}"
    - set_fact: scaleio_tb_primary_hostname="{{ hostvars[groups['tb'][0]]['inventory_hostname'] }}"
    - set_fact: scaleio_tb_secondary_ip="{{ hostvars[groups['tb'][1]]['ansible_'+scaleio_interface]['ipv4']['address'] }}"
      when: hostvars[groups['tb'][1]] is defined

    - set_fact: scaleio_tb_secondary_hostname="{{ hostvars[groups['tb'][1]]['inventory_hostname'] }}"
      when: hostvars[groups['tb'][1]] is defined

    - set_fact: scaleio_mdm_ips="{{ scaleio_mdm_secondary_ip }},{{scaleio_mdm_primary_ip}}"
      when: scaleio_mdm_tertiary_ip is not defined
    - set_fact: scaleio_mdm_ips="{{ scaleio_mdm_secondary_ip }},{{scaleio_mdm_primary_ip}},{{scaleio_mdm_tertiary_ip}}"
      when: scaleio_mdm_tertiary_ip is defined

- hosts: all
  name: "Install ScaleIO Common"
  roles:
    - scaleio_common
  tags: scaleio_common

- hosts: mdm
  name: "Install and configure ScaleIO MDM"
  roles:
    - scaleio_mdm
  tags: scaleio_mdm

- hosts: tb
  name: "Install and configure ScaleIO TB"
  roles:
    - scaleio_tb
  tags: scaleio_tb

#- hosts: gateway
#  name: "Install and configure ScaleIO Gateway"
#  roles:
#    - scaleio_gateway
#  tags: scaleio_gateway

- hosts: sds
  name: "Install and configure ScaleIO SDS"
  roles:
    - scaleio_sds
  tags: scaleio_sds

- hosts: lia
  name: "Install and configure ScaleIO LIA"
  roles:
    - scaleio_lia
  tags: scaleio_lia

- hosts: sdc
  name: "Install and configure ScaleIO SDC"
  roles:
    - scaleio_sdc
  tags: scaleio_sdc

- hosts: gui
  name: "Install ScaleIO GUI"
  roles:
    - scaleio_gui
  tags: scaleio_gui
