--- 
- name: Configure mdm
  hosts: mdm
  roles:
  - common
  - mdm
  - lia

- name: Configure tb
  hosts: tb
  roles:
  - common
  - tb
  - gateway
  - lia

#
# SDS need to happen after MDM's are setup.
#
- name: Configure sds
  hosts: sds
  roles:
  - common
  - sds
