- name: install pre-requisite packages
  yum: name={{ item }} state=latest
  with_items:
  - mutt 
  - bash-completion
  - python

- name: pre-requisite on rhel6 based os
  sysctl: name=kernel.shmmax value=209715200
  when: ansible_os_family == "RedHat" && ansible_distribution_major_version == "6"

- name: copy mdm files
  copy: src={{scaleio_base_package_name}}-{{scaleio_type}}-{{scaleio_version}}.el{{ansible_distribution_major_version}}.x86_64.rpm dest=/var/tmp/ mode=0644 

- name: install mdm package
  yum: name=/var/tmp/{{scaleio_base_package_name}}-{{scaleio_type}}-{{scaleio_version}}.el{{ansible_distribution_major_version}}.x86_64.rpm state=present
