- set_fact: role_name=mdm

- name: install pre-requisite packages
  yum: name={{ item }} state=latest
  with_items:
  - mutt 
  - bash-completion
  - python

- name: pre-requisite on rhel6 based os
  sysctl: name=kernel.shmmax value=209715200
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "6"

- include: ../../install_scaleio.yml 
